config/routes.rb
Rails.application.routes.draw do

  root to: 'lectures#index'

  scope only: [:index, :show] do
    resources :lectures
    resources :assignments
  end

  scope only: :index do
    resources :readings
    resources :resources
  end

  admin_for :lectures, :assignments, :readings, :students, :courses, :users
  admin_for :images, private: true

  namespace :admin do
    root to: 'lectures#index'

    get  'login',  to: 'sessions#new'
    post 'login',  to: 'sessions#create'
    get  'logout', to: 'sessions#destroy'
  end

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  include Brb::Model::Full

  validates_presence_of :title

  has_heading 'Publish On', link: 'publish_on', display: :formatted_date, default: true
  has_heading 'Title', link: 'title'
  has_heading 'Section', link: 'section'
  has_heading 'Active', link: 'active'

  has_and_belongs_to_many :readings, join_table: 'lecture_readings'
  belongs_to :course

  has_content_block :text_block
  has_content_block :image_block
  has_content_block :video_block
  has_content_block :gist_block
  has_content_block :note_block

  def self.active
    where(active: true).order('publish_on DESC')
  end

  def self.published
    where('publish_on <= NOW()').active
  end

  def self.studios
    active.where(section: 'Studio')
  end

  def self.labs
    active.where(section: 'Lab')
  end


  def self.current_studio
    studios.published.first
  end

  def self.current_lab
    labs.published.first
  end

  def readings=(records)
    if records.is_a? String
      courses = Reading.where(id: records.split(',').map(&:to_i))
      super courses
    else
      super
    end
  end

  def formatted_date
    publish_on.strftime('%a, %b %-d, %Y @ %l:%M%P')
  end

end

app/controllers/admin/lectures_controller.rb
class Admin::LecturesController < Admin::ApplicationController
  include Admin::Concerns::PermitParams

  private

  def lecture_params
    params.require(:lecture).permit(
      :title,
      :section,
      :course_id,
      :publish_on,
      :slug,
      :active,
      :grid_view,
      :readings,
      content_block_params,
      standalone_images_params
    )
  end

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController

  def index
    @course = Course.current
    if @current_user.present?
      @lectures = @course.lectures.active
    else
      @lectures = @course.lectures.published
    end

  end

  def show
    @course = Course.current
    @lecture = Lecture.where(active: true, id: params[:id]).first
  end

end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/index.html.erb
<div class="lectures">
  <% @lectures.each do |lecture| %>
    <%= link_to(lecture_path(lecture), class: "band-button #{section_label(lecture)} #{current_record(lecture)}") do %>
      <span class="bug-wrapper">
        <%= section_bug(lecture) %>
      </span>
      <%= ft(lecture.title) %>
    <% end %>
  <% end %>
</div>

app/views/lectures/show.html.erb
<div id="lecture">
  <div class="heading">
    <h2 class="band-button current expanded">
      <%= ft(@lecture.title) %>
    </h2>
  </div>

  <div class="content">
    <% @lecture.content_blocks.each do |cb| %>
      <%= render "content_blocks/#{cb.path_name}/show", cb: cb.send(cb.path_name), x: lightbox_block_index(cb) %>
    <% end %>

    <% if @lecture.readings.present? %>
      <div class="note-block">
        <div class="body">
          <h2>Readings</h2>
          <ol>
          <% @lecture.readings.each do |reading| %>
            <li>
              <%= link_to(pdf_or_url(reading), target: '_blank') do %>
                <%= reading.title %>, <%= reading.author %>
              <%end %>
            </li>
          <% end %>
          </ol>
        </div>
      </div>
    <% end %>

  </div>

</div>