config/routes.rb
Rails.application.routes.draw do

  root to: 'lectures#index'

  scope only: [:index, :show] do
    resources :lectures
    resources :assignments
  end

  scope only: :index do
    resources :readings
    resources :resources
  end

  admin_for :lectures, :assignments, :readings, :students, :courses, :users
  admin_for :images, private: true

  namespace :admin do
    root to: 'lectures#index'

    get  'login',  to: 'sessions#new'
    post 'login',  to: 'sessions#create'
    get  'logout', to: 'sessions#destroy'
  end

end

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3074640-9', 'auto');
  ga('send', 'pageview');
</script>

app/views/shared/_footer.html.erb
<div class="course-info">
  Core Interaction<br />
  <%= @course.semester %> <%= @course.year %>
  <div class="version-number">
    <%= image_tag('crab.gif') %>
    <div class="git-reminder">
      git add .<br />
      git commit -am 'msg ...'<br />
      git push
    </div>
  </div>
</div>

<div class="students">
  <ul>
    <% @course.students.by_name.each do |student| %>
      <li><%= link_to(student.full_name, student.url, target: '_blank') %></li>
    <% end %>
  </ul>
</div>

<% content_for :init_student_list do %>
<script type="text/javascript">
  var students = [];
      students = <%= raw(@course.students.flat_list) %>;
  if (students.length > 0) {
    init_wheel_of_fortune(students);
  }
</script>
<% end %>

app/views/shared/_header.html.erb
<div class="inner">
  <ul id="filters">
    <% if page_name == 'lectures-index' || page_name == 'assignments-index' || page_name == 'readings-index' %>
    <li><span class="bug all active" data-target="all"><span class="letter">All</span></span></li>
    <li><span class="bug studio off" data-target="studio"><span class="letter">Studio</span></span></li>
    <li><span class="bug lab off" data-target="lab"><span class="letter">Lab</span></span></li>
    <% else %>
    <li><a href="/"><span class="bug lab" data-target="lab"><span class="letter">&#9664; Back</span></span></a></li>
    <% end %>
  </ul>

  <ul id="navigation">
    <li><%= nav_link('Lectures',    lectures_path) %></li>
    <li><%= nav_link('Assignments', assignments_path) %></li>
    <li><%= nav_link('Readings',    readings_path) %></li>
    <li><%= nav_link('Resources',   resources_path) %></li>
  </ul>
</div>

app/views/shared/_wheel_of_fortune.html.erb
<div class="wheel-wrap">
	<div id="wheel-of-fortune">
		<div id="table-container"></div>
	</div>
	<div id="remain"></div>
	<div id="blackout"></div>
</div>